#!/bin/bash

PATH=$1

if [[ $1 = '--fix' ]]
then
  PATH=$2
fi

node -e 'console.log(42);'

if [[ $1 = '--fix' || $2 = '--fix' ]]
then
  ./node_modules/.bin/tslint -c migrate.json $PATH --fix
else
  ./node_modules/.bin/tslint -c migrate.json $PATH
fi
